config/routes.rb
Rails.application.routes.draw do
  get "seasons/index"
  get "/seasons/:id", to: "seasons#show", as: "season"
  get "circuits/index"
  get "/circuits/:id", to: "circuits#show", as: "circuit"
  get "laptimes/index"
  get "/laptimes/:id", to: "laptimes#show", as: "laptime"
  get "drivers/index"
  get "/drivers/:id", to: "drivers#show", as: "driver"
  get "home/index"
  get "home/about"
  post "home/search", to: "home#search", as: "search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circuit.rb
class Circuit < ApplicationRecord
  has_many :laptimes
  has_and_belongs_to_many :seasons
  validates :name, :locality, :country, presence: true
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :laptimes
  validates :first_name, :last_name, presence: true
end

app/models/laptime.rb
class Laptime < ApplicationRecord
  belongs_to :driver
  belongs_to :circuit, optional: true
  belongs_to :season,  optional: true
  validates :laptime, :driver_id, presence: true
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :laptimes
  has_and_belongs_to_many :circuits
  validates :year, :url, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController
  def index
    root_query = Circuit.includes(:seasons, :laptimes).all
    unless params[:search] == "" || params[:search].nil?
      root_query = if params[:category] == "Circuits"
                     root_query.where(name: params[:search])
                   elsif params[:category] == "Seasons"
                     root_query.where(seasons: { year: params[:search] })
                   else
                     root_query.where(laptimes: { laptime: params[:search] })
                   end
    end
    @circuits = root_query
    @categories = ["Circuits", "Seasons", "Laptimes"]
    @current_selection = (params[:category] || @categories[0])
  end

  def show
    @circuit = Circuit.find(params[:id])
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    root_query = Driver.includes(:laptimes).all
    unless params[:search] == "" || params[:search].nil?
      root_query = if params[:category] == "Drivers"
                     root_query.where(first_name: params[:search]).or(root_query.where(last_name: params[:search]))
                   else
                     root_query.where(laptimes: { laptime: params[:search] })
                   end

    end
    @drivers = root_query
    @categories = ["Drivers", "Laptimes"]
    @current_selection = (params[:category] || @categories[0])
  end

  def show
    @driver = Driver.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end

  def search
    puts "Made it!"
  end
end

app/controllers/laptimes_controller.rb
class LaptimesController < ApplicationController
  def index
    root_query = Laptime.includes(:season, :driver, :circuit).all

    unless params[:search] == "" || params[:search].nil?
      root_query = if params[:category] == "Laptimes"
                     root_query.where(laptime: params[:search])
                   elsif params[:category] == "Circuits"
                     root_query.where(circuits: { name: params[:search] })
                   elsif params[:category] == "Seasons"
                     root_query.where(Seasons: { year: params[:search] })
                   else
                     root_query.where(Drivers: { first_name: params[:search] }).or(root_query.where(Drivers: { last_name: params[:search] }))
                   end
    end
    @laptimes = root_query
    @categories = ["Laptimes", "Circuits", "Seasons", "Drivers"]
    @current_selection = (params[:category] || @categories[0])
  end

  def show
    @laptime = Laptime.find(params[:id])
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    root_query = Season.includes(:circuits, :laptimes).all

    unless params[:search] == "" || params[:search].nil?
      root_query = if params[:category] == "Seasons"
                     root_query.where(year: params[:search])
                   elsif params[:category] == "Circuits"
                     root_query.where(circuits: { name: params[:search] })
                   else
                     root_query.where(laptimes: { laptime: params[:search] })
                   end
    end
    @seasons = root_query
    @categories = ["Seasons", "Circuits", "Laptimes"]
    @current_selection = (params[:category] || @categories[0])
  end

  def show
    @season = Season.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circuits_helper.rb
module CircuitsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/laptimes_helper.rb
module LaptimesHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/circuits/index.html.erb
<div class="ml-4">
  <h1 class="title">Circuits</h1>

  <%= render 'layouts/search' %>

  <table class="table">
    <% @circuits.each do |circuit| %>
      <tr>
        <td><%= link_to circuit.name, circuit_path(circuit) %></td>
        <td><%= circuit.country %></td>
      </tr>
    <% end %>
  </table>

</div>

app/views/circuits/show.html.erb
<div class="ml-4 mr-4">
  <h1 class="title"><%= @circuit.name %></h1>
  <p class="has-text-weight-bold"><%= @circuit.country %></p>
  <p class="has-text-weight-bold"><%= @circuit.locality %></p>
  <br>

  <h3 class="title is-6">Seasons:</h3>
  <ul id="seasons-ul">
    <% @circuit.seasons.each do |season| %>
      <li><%= link_to season.year, season_path(season) %></li>
    <% end %>
  </ul>
  <br>
  <br>
  <br>
  <h3 class="title is-6">Laptimes</h3>
  <% if @circuit.laptimes.count == 0 %>
    <p>No results for circuits used before '96.</p>
  <% else %>
    <table class="table">
    <% @circuit.laptimes.each do |laptime| %>
      <tr>
        <td><%=link_to laptime.driver.first_name, driver_path(laptime.driver)%></td>
        <td><%=link_to laptime.driver.last_name, driver_path(laptime.driver)%></td>
        <td><%=link_to laptime.laptime, laptime_path(laptime)%></td>
        <td><%=link_to laptime.season.year, season_path(laptime.season)%></td>
      </tr>
    <% end %>
    </table>
  <% end %>
</div>

app/views/drivers/index.html.erb
<div class="ml-4">
  <h1 class="title">Drivers</h1>

  <%= render 'layouts/search' %>

  <table class="table">
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= link_to driver.first_name, driver_path(driver) %></td>
        <td><%= link_to driver.last_name, driver_path(driver) %></td>
        <td><%= driver.dob %></td>
        <td><%= driver.nationality %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/drivers/show.html.erb
<div class="ml-4">
  <h1 class="title"><%= @driver.last_name %>, <%= @driver.first_name %></h1>
  <h3>Born: <%= @driver.dob %></h3>
  <h3>Nationality: <%= @driver.nationality %></h3>
  <h3>Wiki Article: <a href="<%= @driver.url %>">Article</a></h3>
  <br>
  <% if @driver.laptimes.count == 0 %>
    <p>No laptimes available.</p>
  <% else %>
    <h3 class="title is-6">Laptimes</h3>
    <table class="table">
      <% @driver.laptimes.each do |laptime| %>
        <tr>
          <td><%=link_to laptime.laptime, laptime_path(laptime)%></td>
          <td><%=link_to laptime.circuit.name, circuit_path(laptime.circuit)%></td>
          <td><%=link_to laptime.season.year, season_path(laptime.season)%></td>
        </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/home/about.html.erb
<div class="ml-4 mr-6">
  <h1 class="title">Welcome to my midterm project!</h1>
  <p class="subtitle">This application takes information from a Formula 1 API and parses it into some readable information.</p>
  <br/>
  <p>I will be pulling data from an F1 standing source located at http://ergast.com/api/f1/. This dataset contains information on formula 1 season standings from 1950 to 2020. The data I will be using is: Season information, driver information, laptime records, and circuits. The data will be organized into 4 main tables: Circuits, Seasons, Drivers and lap times.
  Columns: Seasons will contain the date of the series and a link to its Wikipedia article
  Circuits will contain information about which season they belong to (many to many relationship, new table will be required to resolve this), a URL to more information about the track, its locality and country.
  Drivers will contain information about a driver name, date of birth and nationality, along with a link to their Wikipedia page.
  Lap times will contain which driver they’re associated with, what track they were set on, and what season they were set, in addition to the actual time.
  </p>
  <br>
  <p>Table relations: Seasons and circuits will have a many to many relationship as a circuit can be used in many seasons and a season will have many circuits. A season will have many drivers and a driver can race for many seasons. A driver will have several lap times associated with them. A lap time will belong to one driver, one season and one track.</p>
  <br>
  <h2>Here's an ERD:</h2>
</div>


<img src="/images/erd.jpg" alt="Model ERD">

app/views/home/index.html.erb
<div class="ml-4">
  <h1 class="title">F1 Race Standings</h1>
  <p class="subtitle">Hey, glad you're here. I don't really have much to say, but feel free to take a look around.</p>
</div>

app/views/laptimes/index.html.erb
<div class="ml-4 mr-4">
  <h1 class="title">Laptimes</h1>

  <%= render 'layouts/search' %>

  <ul id="laptimes-ul">
    <% @laptimes.each do |laptime| %>
      <li><%= link_to laptime.laptime, laptime_path(laptime) %></li>
    <% end %>
  </ul>
</div>

app/views/laptimes/show.html.erb
<div class="ml-4">
  <h3 class="title"><%= @laptime.laptime %></h3>

  <p>Set by <%=link_to @laptime.driver.first_name, driver_path(@laptime.driver)%>
  <%=link_to @laptime.driver.last_name, driver_path(@laptime.driver)%> on
  <%=link_to @laptime.circuit.name, circuit_path(@laptime.circuit)%> in
  <%=link_to @laptime.season.year, season_path(@laptime.season)%></p>
</div>

app/views/layouts/_search.html.erb
<br>
<%= form_tag action_name, :name => "searchForm", method: :get do %>
  <%= search_field_tag :search, params[:search], placeholder: "Search" %>
  <%= select_tag :category, options_for_select(@categories, @current_selection) %>
  <%= submit_tag "Search" %>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Racestandings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item">
          <img src="https://www.flaticon.com/svg/static/icons/svg/79/79700.svg" width="28" height="28" alt="F1 Race Standings">
        </a>
      </div>

      <div id="mainNav" class="navbar-menu">
        <div class="navbar-start">
          <%= link_to "Home", "/", class: "navbar-item"%>

          <%= link_to "Seasons", "/seasons/index", class: "navbar-item"%>

          <%= link_to "Circuits", "/circuits/index", class: "navbar-item"%>

          <%= link_to "Laptimes", "/laptimes/index", class: "navbar-item"%>

          <%= link_to "Drivers", "/drivers/index", class: "navbar-item"%>
        </div>

        <div class="navbar-end">
          <%= link_to "About", "/home/about", class: "navbar-item" %>
        </div>
      </div>
    </nav>
    <%= yield %>

  </body>
</html>

app/views/seasons/index.html.erb
<div id="seasons-div" class="ml-4 mr-4">
  <h1 class="title">Seasons</h1>

  <%= render 'layouts/search'%>

  <ul id="seasons-ul">
    <% @seasons.each do |season| %>
      <li><%= link_to season.year,  season_path(season)%></li>
    <% end %>
  </ul>
</div>

app/views/seasons/show.html.erb
<div class="ml-4">
  <h1 class="title"><%= @season.year %></h1>
  <p class="subtitle"><a href="<%= @season.url %>">Season wikipedia link</a></p>
  <br>
  <% @season.circuits.each do |circuit| %>
    <h3 class="title is-5"><%= link_to circuit.name, circuit_path(circuit) %></h3>
    <% if @season.year >= 1996 && @season.year < 2020 %>
      <h4 class="subtitle">Lap times:</h4>
    <% end %>
      <table class="table">
      <% circuit.laptimes.where(season: @season).each do |laptime| %>
        <tr>
          <td><%=link_to laptime.driver.first_name, driver_path(laptime.driver)%></td>
          <td><%=link_to laptime.driver.last_name, driver_path(laptime.driver)%></td>
          <td><%=link_to laptime.laptime, laptime_path(laptime)%></td>
        </tr>
      <% end %>
    </table>
    <br>
  <% end %>
</div>